### ISSUE TITLE
super repozytorium

### ISSUE THREAD

**Issue by kvdrrrrr** [beeniz/Flex.css#1]
naprawde bardzo fajne repozytorium :)

**Comment by kvdrrrrr** [comment]
![88213049_1044597412579913_3130934962256122579_n-edit](https://user-images.githubusercontent.com/23129500/76713489-2e80dc00-6721-11ea-9a40-6fbf81fb7368.png)

**Comment by beeniz** [comment]
witam dziekuje za komentarz lecz proszę o pisanie w języku angielskim oraz nie używanie słów używanych powszechnie za wulgarne.

-------------
Piszę poprawnie po polsku.
